# Generated by Django 2.1.5 on 2019-02-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField()),
                ('booked_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('booked_days', models.IntegerField(blank=True, default=0, null=True)),
                ('deadline', models.DateTimeField(blank=True, default=None, null=True)),
                ('block_floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RoomService.BlockFloor')),
                ('booked_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True)),
                ('room_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RoomService.RoomType'),
        ),
        migrations.AddField(
            model_name='blockfloor',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RoomService.Floor'),
        ),
    ]
